/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type CuisineType = { 'japanese' : null } |
  { 'chinese' : null } |
  { 'italian' : null } |
  { 'indian' : null } |
  { 'american' : null };
export interface MenuItem {
  'id' : MenuItemId,
  'name' : string,
  'isAvailable' : boolean,
  'description' : string,
  'restaurantId' : RestaurantId,
  'category' : string,
  'price' : number,
}
export type MenuItemId = bigint;
export interface Order {
  'id' : OrderId,
  'status' : OrderStatus,
  'userId' : Principal,
  'createdAt' : Time,
  'restaurantId' : RestaurantId,
  'totalAmount' : number,
  'items' : Array<OrderItem>,
}
export type OrderId = bigint;
export interface OrderItem {
  'name' : string,
  'quantity' : bigint,
  'price' : number,
  'menuItemId' : MenuItemId,
}
export type OrderStatus = { 'preparing' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'onTheWay' : null } |
  { 'delivered' : null };
export interface Restaurant {
  'id' : RestaurantId,
  'name' : string,
  'cuisineType' : CuisineType,
  'description' : string,
  'isActive' : boolean,
  'deliveryTimeMinutes' : bigint,
  'rating' : number,
}
export type RestaurantId = bigint;
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addMenuItem' : ActorMethod<[MenuItem], undefined>,
  'addRestaurant' : ActorMethod<[Restaurant], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllActiveRestaurants' : ActorMethod<[], Array<Restaurant>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMenuItemsByRestaurant' : ActorMethod<[RestaurantId], Array<MenuItem>>,
  'getOrder' : ActorMethod<[OrderId], Order>,
  'getUserOrders' : ActorMethod<[], Array<Order>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<[RestaurantId, Array<OrderItem>], OrderId>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedData' : ActorMethod<[], undefined>,
  'updateMenuItemAvailability' : ActorMethod<[MenuItemId, boolean], undefined>,
  'updateOrderStatus' : ActorMethod<[OrderId, OrderStatus], undefined>,
  'updateRestaurant' : ActorMethod<[RestaurantId, Restaurant], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];