/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MenuItemId = IDL.Nat;
export const RestaurantId = IDL.Nat;
export const MenuItem = IDL.Record({
  'id' : MenuItemId,
  'name' : IDL.Text,
  'isAvailable' : IDL.Bool,
  'description' : IDL.Text,
  'restaurantId' : RestaurantId,
  'category' : IDL.Text,
  'price' : IDL.Float64,
});
export const CuisineType = IDL.Variant({
  'japanese' : IDL.Null,
  'chinese' : IDL.Null,
  'italian' : IDL.Null,
  'indian' : IDL.Null,
  'american' : IDL.Null,
});
export const Restaurant = IDL.Record({
  'id' : RestaurantId,
  'name' : IDL.Text,
  'cuisineType' : CuisineType,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'deliveryTimeMinutes' : IDL.Nat,
  'rating' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const OrderId = IDL.Nat;
export const OrderStatus = IDL.Variant({
  'preparing' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'onTheWay' : IDL.Null,
  'delivered' : IDL.Null,
});
export const Time = IDL.Int;
export const OrderItem = IDL.Record({
  'name' : IDL.Text,
  'quantity' : IDL.Nat,
  'price' : IDL.Float64,
  'menuItemId' : MenuItemId,
});
export const Order = IDL.Record({
  'id' : OrderId,
  'status' : OrderStatus,
  'userId' : IDL.Principal,
  'createdAt' : Time,
  'restaurantId' : RestaurantId,
  'totalAmount' : IDL.Float64,
  'items' : IDL.Vec(OrderItem),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addMenuItem' : IDL.Func([MenuItem], [], []),
  'addRestaurant' : IDL.Func([Restaurant], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllActiveRestaurants' : IDL.Func([], [IDL.Vec(Restaurant)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMenuItemsByRestaurant' : IDL.Func(
      [RestaurantId],
      [IDL.Vec(MenuItem)],
      ['query'],
    ),
  'getOrder' : IDL.Func([OrderId], [Order], ['query']),
  'getUserOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func([RestaurantId, IDL.Vec(OrderItem)], [OrderId], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'seedData' : IDL.Func([], [], []),
  'updateMenuItemAvailability' : IDL.Func([MenuItemId, IDL.Bool], [], []),
  'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [], []),
  'updateRestaurant' : IDL.Func([RestaurantId, Restaurant], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MenuItemId = IDL.Nat;
  const RestaurantId = IDL.Nat;
  const MenuItem = IDL.Record({
    'id' : MenuItemId,
    'name' : IDL.Text,
    'isAvailable' : IDL.Bool,
    'description' : IDL.Text,
    'restaurantId' : RestaurantId,
    'category' : IDL.Text,
    'price' : IDL.Float64,
  });
  const CuisineType = IDL.Variant({
    'japanese' : IDL.Null,
    'chinese' : IDL.Null,
    'italian' : IDL.Null,
    'indian' : IDL.Null,
    'american' : IDL.Null,
  });
  const Restaurant = IDL.Record({
    'id' : RestaurantId,
    'name' : IDL.Text,
    'cuisineType' : CuisineType,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'deliveryTimeMinutes' : IDL.Nat,
    'rating' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const OrderId = IDL.Nat;
  const OrderStatus = IDL.Variant({
    'preparing' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'onTheWay' : IDL.Null,
    'delivered' : IDL.Null,
  });
  const Time = IDL.Int;
  const OrderItem = IDL.Record({
    'name' : IDL.Text,
    'quantity' : IDL.Nat,
    'price' : IDL.Float64,
    'menuItemId' : MenuItemId,
  });
  const Order = IDL.Record({
    'id' : OrderId,
    'status' : OrderStatus,
    'userId' : IDL.Principal,
    'createdAt' : Time,
    'restaurantId' : RestaurantId,
    'totalAmount' : IDL.Float64,
    'items' : IDL.Vec(OrderItem),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addMenuItem' : IDL.Func([MenuItem], [], []),
    'addRestaurant' : IDL.Func([Restaurant], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllActiveRestaurants' : IDL.Func([], [IDL.Vec(Restaurant)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMenuItemsByRestaurant' : IDL.Func(
        [RestaurantId],
        [IDL.Vec(MenuItem)],
        ['query'],
      ),
    'getOrder' : IDL.Func([OrderId], [Order], ['query']),
    'getUserOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func([RestaurantId, IDL.Vec(OrderItem)], [OrderId], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'seedData' : IDL.Func([], [], []),
    'updateMenuItemAvailability' : IDL.Func([MenuItemId, IDL.Bool], [], []),
    'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [], []),
    'updateRestaurant' : IDL.Func([RestaurantId, Restaurant], [], []),
  });
};

export const init = ({ IDL }) => { return []; };